name: Compile and Publish Docker Image

on:
  push:
    tags:
      - 'v*' # Executa a action quando uma tag for "v1.0.0", "v2.1", etc.

env:
  # Pode ser trocado pelo domínio ou IP local do seu Gitea (ex: gitea.local:3000)
  # Ou se estiver enviando para o Docker Hub, mude para: docker.io
  REGISTRY: notebook-server:3000
  
jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest # Requer que um runner do Gitea (act_runner) esteja configurado
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Container Registry (Gitea)
        uses: docker/login-action@v3
        with:
          registry: http://notebook-server:3000
          username: ${{ github.actor }}
          password: ${{ secrets.GITEA_TOKEN }}
          # Nota: no Gitea, secrets.GITHUB_TOKEN representa o token da própria action

      # ----- DOCKER BACKEND ----- #
      - name: Metadados da Imagem - Backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ gitea.repository_owner }}/tech-diary-backend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - name: Compilar e Publicar a Imagem (Backend)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      # ----- DOCKER FRONTEND ----- #
      - name: Metadados da Imagem - Frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ gitea.repository_owner }}/tech-diary-frontend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - name: Compilar e Publicar a Imagem (Frontend)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
